app = "svr-backend"
primary_region = "ewr"  # Choose a region close to your users

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "svr_data"
  destination = "/app/local_storage"

[env]
  STORAGE_TYPE = "local" 